services:
  - type: web
    name: gabesi-fastapi
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: OPENAI_API_KEY
        sync: false
      - key: QDRANT_URL
        sync: false
      - key: QDRANT_API_KEY
        sync: false
      - key: LANGCHAIN_API_KEY
        sync: false
      - key: LANGCHAIN_TRACING_V2
        value: "true"
      - key: LANGCHAIN_PROJECT
        value: "Gabes"
      - key: LANGCHAIN_ENDPOINT
        value: "https://api.smith.langchain.com"
      - key: KMP_DUPLICATE_LIB_OK
        value: "TRUE"
      - key: OMP_NUM_THREADS
        value: "1"

  - type: web
    name: gabesi-flask
    runtime: python
    rootDir: emergency_intel
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: OPENAI_API_KEY
        sync: false
      - key: QDRANT_URL
        sync: false
      - key: QDRANT_API_KEY
        sync: false
      - key: SERPAPI_KEY
        sync: false
